---
- name: This is a playbook for AVD golden image (base config)
  hosts: windows
  gather_facts: true
  
  pre_tasks:
    - debug:
        msg: "Pre activity from here"
  
  roles: 
    #- fslogix
    #- office
    #- osconfig
    - generalize

  post_tasks:
    - debug:
        msg: "Post activity from here"
